Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true

### mysql vm  ####
config.vm.define "db01" do |db01|
  db01.vm.box = "geerlingguy/centos7"
  db01.vm.hostname = "db01"
  db01.vm.network "private_network", ip: "192.168.56.14"
  db01.vm.provision "shell", path: "mysql.sh"  
end
  
### Memcache vm  #### 
config.vm.define "mc01" do |mc01|
  mc01.vm.box = "geerlingguy/centos7"
  mc01.vm.hostname = "mc01"
  mc01.vm.network "private_network", ip: "192.168.56.12"
  mc01.vm.provision "shell", path: "memcache.sh"  
end

### RabbitMQ vm  ####
config.vm.define "rmq01" do |rmq01|
  rmq01.vm.box = "geerlingguy/centos7"
rmq01.vm.hostname = "rmq01"
  rmq01.vm.network "private_network", ip: "192.168.56.13"
  rmq01.vm.provision "shell", path: "rabbitmq.sh"  
end

### flask app ###
config.vm.define "app01" do |app01|
  app01.vm.box = "ubuntu/focal64"
  app01.vm.hostname = "app01"
  app01.vm.network "private_network", ip: "192.168.56.11" 
  app01.vm.provision "shell", path: "app.sh" 
  app01.vm.provider "virtualbox" do |vb|
   vb.memory = "1024"
  end
end

config.vm.define "app02" do |app02|
  app02.vm.box = "ubuntu/focal64"
  app02.vm.hostname = "app02"
  app02.vm.network "private_network", ip: "192.168.56.15" 
  app02.vm.provision "shell", path: "app.sh" 
  app02.vm.provider "virtualbox" do |vb|
   vb.memory = "1024"
  end
end
  
### nginx vm  ####
config.vm.define "lb01" do |lb01|
  lb01.vm.box = "ubuntu/focal64"
  lb01.vm.hostname = "lb01"
  lb01.vm.network "private_network", ip: "192.168.56.16"
  lb01.vm.provision "shell", path: "nginx.sh"  
  lb01.vm.provider "virtualbox" do |vb|
   vb.memory = "1024"
  end
end

config.vm.define "appprod" do |appprod|
  appprod.vm.box = "ubuntu/focal64"
  appprod.vm.hostname = "appprod"
  appprod.vm.network "private_network", ip: "192.168.56.20"  
  appprod.vm.provider "virtualbox" do |vb|
   vb.memory = "1024"
  end
end

end
